version: "3"
services:
  lazytainer:
    container_name: lazytainer
    image: ghcr.io/vmorganp/lazytainer:master
    environment:
      - PORT=81,82           # comma separated list of ports...or just the one 
      - LABEL=lazytainer     # value of lazytainer.marker for other containers that lazytainer checks
      # - TIMEOUT=30         # OPTIONAL number of seconds to let container idle
      # - MINPACKETTHRESH=10 # OPTIONAL number of packets that must be recieved to keepalive/start container 
      # - POLLRATE=5         # OPTIONAL number of packets that must be recieved to keepalive/start container 
      # - VERBOSE=true
    ports:
      - 81:81
      - 82:82
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  whoami1:
    container_name: whoami1
    image: containous/whoami
    command: --port 81
    network_mode: service:lazytainer
    depends_on: 
      - lazytainer
    labels:
      - "lazytainer.marker=lazytainer"

  whoami2:
    container_name: whoami2
    image: containous/whoami
    command: --port 82
    network_mode: service:lazytainer
    depends_on: 
      - lazytainer
    labels:
      - "lazytainer.marker=lazytainer"