version: "3"
services:
  sandman:
    container_name: sandman
    build: .
    environment:
      - PORT=81 # TODO make this work with more than one port
      - LABEL=sandman # sandman checks
      - TIMEOUT=30 # number of seconds to let container idle
    ports:
      - 81:81
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  whoami2:
    container_name: whoami2
    image: containous/whoami
    command: --port 81
    network_mode: service:sandman
    depends_on: 
      - sandman
    # ports:
    # - 80:80
    labels:
      - "com.sandman.marker=sandman"