version: "3"
services:
  lazytainer:
    container_name: lazytainer
    image: ghcr.io/vmorganp/lazytainer:master
    environment:
      - PORT=25565 
      - LABEL=lazytainer
      - TIMEOUT=900
    ports:
      - 25565:25565
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  mc:
    image: itzg/minecraft-server:java8-multiarch
    network_mode: service:lazytainer
    environment:
      EULA: "TRUE"
      TYPE: FTBA
      FTB_MODPACK_ID: 79 # direwolf20 1.16
      # MEMORYSIZE: 15G
      # MEMORY: 15G
    restart: unless-stopped
    labels:
      - "lazytainer.marker=lazytainer"
    depends_on: 
      - lazytainer
    volumes:
      - /home/temp/mc:/data